tesselo/urls.py
from django.conf.urls import include, url
from django.contrib.gis import admin
from rest_framework.documentation import include_docs_urls
from rest_framework.permissions import IsAdminUser
from tesselo.apiurls import apiurlpatterns

urlpatterns = [
    url(r'^docs/', include_docs_urls(title='Tesselo API Docs', public=False, permission_classes=[IsAdminUser])),
    url(r'^accounts/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^admin/', admin.site.urls),
]

urlpatterns += apiurlpatterns

apps/report/models.py
import datetime

from django.contrib.postgres.fields import JSONField
from django.db import models
from django.db.models.signals import post_delete, pre_save
from django.dispatch import receiver
from raster.tiles.const import WEB_MERCATOR_SRID
from raster_aggregation.models import AggregationArea, AggregationLayer, ValueCountResult
from rasterio.crs import CRS

from classify.models import PredictedLayer
from report.const import ALLOWED_LINEAR_UNITS
from sentinel.models import Composite


class ReportSchedule(models.Model):
    """
    Schedule automatic aggregation over an aggregationlayer using every
    combination of the formulas, composites, and predicted layers specified.
    """
    name = models.CharField(max_length=200, default='')
    aggregationlayers = models.ManyToManyField(AggregationLayer)
    formulas = models.ManyToManyField('formulary.Formula')
    composites = models.ManyToManyField(Composite)
    predictedlayers = models.ManyToManyField(PredictedLayer)
    active = models.BooleanField(default=False)

    def __str__(self):
        return '{} | {} | {}'.format(self.id, self.name, 'Active' if self.active else 'Deactivated')


class ReportScheduleTask(models.Model):
    """
    Track one long running async task to compute aggregation values.
    """
    UNPROCESSED = 'Unprocessed'
    PENDING = 'Pending'
    PROCESSING = 'Processing'
    FINISHED = 'Finished'
    FAILED = 'Failed'
    ST_STATUS_CHOICES = (
        (UNPROCESSED, UNPROCESSED),
        (PENDING, PENDING),
        (PROCESSING, PROCESSING),
        (FINISHED, FINISHED),
        (FAILED, FAILED),
    )

    aggregationlayer = models.ForeignKey(AggregationLayer, on_delete=models.CASCADE)
    formula = models.ForeignKey('formulary.Formula', on_delete=models.CASCADE, blank=True, null=True)
    composite = models.ForeignKey(Composite, on_delete=models.CASCADE, blank=True, null=True)
    predictedlayer = models.ForeignKey(PredictedLayer, on_delete=models.CASCADE, blank=True, null=True)

    status = models.CharField(max_length=20, choices=ST_STATUS_CHOICES, default=UNPROCESSED)
    log = models.TextField(default='', blank=True)

    def __str__(self):
        return '{} | Agg {}, Comp {}, Form {}, Pred {}'.format(
            self.id,
            self.aggregationlayer,
            self.composite,
            self.formula,
            self.predictedlayer,
        )

    def write(self, data, status=None):
        now = '[{0}] '.format(datetime.datetime.now().strftime('%Y-%m-%d %T'))
        self.log += now + str(data) + '\n'
        if status:
            self.status = status
        self.save()


class ReportAggregation(models.Model):
    """
    Aggregate Sentinel-2 data by formula and aggregation area.
    """

    ZOOM = 14
    VALUECOUNT_ROUNDING_DIGITS = 7

    formula = models.ForeignKey('formulary.Formula', on_delete=models.CASCADE, blank=True, null=True, help_text='Leave empty for predicted layers.')
    aggregationlayer = models.ForeignKey(AggregationLayer, on_delete=models.CASCADE)
    aggregationarea = models.ForeignKey(AggregationArea, on_delete=models.CASCADE)

    composite = models.ForeignKey(Composite, on_delete=models.CASCADE, blank=True, null=True)
    predictedlayer = models.ForeignKey(PredictedLayer, on_delete=models.CASCADE, blank=True, null=True)

    valuecountresult = models.OneToOneField(ValueCountResult, on_delete=models.CASCADE, blank=True)

    min_date = models.DateField(null=True, blank=True, editable=False, db_index=True)
    max_date = models.DateField(null=True, blank=True, editable=False, db_index=True)

    value = JSONField(default=dict, db_index=True)
    value_percentage = JSONField(default=dict, db_index=True)

    stats_min = models.FloatField(editable=False, blank=True, null=True, db_index=True)
    stats_max = models.FloatField(editable=False, blank=True, null=True, db_index=True)
    stats_avg = models.FloatField(editable=False, blank=True, null=True, db_index=True)
    stats_std = models.FloatField(editable=False, blank=True, null=True, db_index=True)

    stats_cumsum_t0 = models.FloatField(editable=False, blank=True, null=True, help_text='Nr of pixels counted.')
    stats_cumsum_t1 = models.FloatField(editable=False, blank=True, null=True, help_text='Sum of pixel values.')
    stats_cumsum_t2 = models.FloatField(editable=False, blank=True, null=True, help_text='Sum of squares of pixel values.')

    stats_percentage_covered = models.FloatField(editable=False, blank=True, null=True, help_text='Percentage of area covered by valid pixels.')

    srid = models.IntegerField(editable=False, default=WEB_MERCATOR_SRID, help_text='SRID used for this aggregation.')

    def __str__(self):
        dat = '{}'.format(self.id)
        if hasattr(self, 'aggregationlayer') and self.aggregationlayer:
            dat += ' | {}'.format(self.aggregationlayer.name)
        if hasattr(self, 'composite') and self.composite:
            dat += ' | {}'.format(self.composite.name)
        if hasattr(self, 'formula') and self.formula:
            dat += ' | {}'.format(self.formula.name)
        if hasattr(self, 'predictedlayer') and self.predictedlayer:
            dat += ' | Pred {}'.format(self.predictedlayer.id)
        return dat

    def get_valuecount(self):
        # Get data for valuecount result update.
        if self.composite:
            formula = self.formula.formula
            range_min = self.formula.min_val
            range_max = self.formula.max_val
            layer_names = {
                key.replace('.jp2', '').replace('0', ''): val for key, val in self.composite.rasterlayer_lookup.items()
            }
            # Only keep bands that are present in formula.
            layer_names = {key: val for key, val in layer_names.items() if key in formula}
            # Add predictedlayer keys to lookup.
            for pred in self.formula.predictedlayerformula_set.all():
                layer_names[pred.key] = pred.predictedlayer.rasterlayer_id
        elif self.predictedlayer_id:
            # Simple formula for predictedlayers.
            formula = 'x'
            layer_names = {'x': self.predictedlayer.rasterlayer_id}
            range_min = None
            range_max = None
        else:
            raise ValueError('Specify Composite or PredictedLayer.')

        # Remove existing valuecounts.
        if hasattr(self, 'valuecountresult') and self.valuecountresult is not None:
            self.valuecountresult.delete()

        # Choose grouping.
        if (self.formula and self.formula.discrete) or self.predictedlayer_id:
            grouping = 'discrete'
        else:
            grouping = 'continuous'

        # Setup new valuecount without storing it yet.
        return ValueCountResult(
            layer_names=layer_names,
            formula=formula,
            range_min=range_min,
            range_max=range_max,
            zoom=self.ZOOM,
            aggregationarea=self.aggregationarea,
            units='acres',
            grouping=grouping,
        )

    def copy_valuecount(self):
        # Copy the data to the ReportAggregation.
        self.value = {key: float(value) for key, value in self.valuecountresult.value.items()}
        self.stats_min = self.valuecountresult.stats_min
        self.stats_max = self.valuecountresult.stats_max
        self.stats_avg = self.valuecountresult.stats_avg
        self.stats_std = self.valuecountresult.stats_std
        self.stats_cumsum_t0 = self.valuecountresult.stats_cumsum_t0
        self.stats_cumsum_t1 = self.valuecountresult.stats_cumsum_t1
        self.stats_cumsum_t2 = self.valuecountresult.stats_cumsum_t2

        # Compute percentage by value.
        valsum = sum([float(val) for key, val in self.valuecountresult.value.items()])
        if valsum != 0:
            self.value_percentage = {key: float(val) / valsum for key, val in self.valuecountresult.value.items()}

    @property
    def geom_4326(self):
        return self.aggregationarea.geom_simplified.transform(4326, clone=True)


@receiver(post_delete, sender=ReportAggregation, weak=False, dispatch_uid="remove_valuecount_before_delete")
def check_change_on_formula(sender, instance, **kwargs):
    if hasattr(instance, 'valuecountresult'):
        instance.valuecountresult.delete()


@receiver(pre_save, sender=ReportAggregation, weak=False, dispatch_uid="auto_set_valuecountresult_min_max_dates")
def auto_set_valuecountresult_min_max_dates(sender, instance, **kwargs):
    if instance.composite:
        src_object = instance.composite
    elif instance.predictedlayer:
        src_object = instance.predictedlayer
    else:
        return

    instance.min_date = src_object.min_date
    instance.max_date = src_object.max_date


class ReportAggregationLayerSrid(models.Model):
    """
    Tag an aggregationlayer with an SRID that will be used to compute the report
    data.
    """
    aggregationlayer = models.OneToOneField(AggregationLayer, on_delete=models.CASCADE)
    srid = models.IntegerField(help_text='Specify an SRID for computing all aggregations on this layer. The unit of the srid is required to be in meters.')

    def __str__(self):
        return '{} | {}'.format(self.aggregationlayer.name, self.srid)

    def save(self, *args, **kwargs):
        # Remove any non-alphanumeric characters from the key.
        crs = CRS.from_epsg(self.srid)
        units = crs.linear_units.lower()
        if units not in ALLOWED_LINEAR_UNITS:
            raise ValueError('Only meter or metre are allowed as linear units. Found "{}".'.format(units))
        super().save(*args, **kwargs)

apps/auth_admin/templates/initialize_customer.html
{% extends "admin/base_site.html" %}
{% load i18n admin_urls static admin_modify %}


{% block extrahead %}{{ block.super }}
    <script type="text/javascript" src="{% url 'admin:jsi18n' %}"></script>
    {{ media }}
    {{ date_form.media }}
{% endblock %}

{% block extrastyle %}{{ block.super }}
    <link rel="stylesheet" type="text/css" href="{% static "admin/css/forms.css" %}">{% endblock %}

{% block coltype %}colM{% endblock %}

{% block bodyclass %}{{ block.super }} app-{{ opts.app_label }} model-{{ opts.model_name }} change-form{% endblock %}


{% block content %}
    <div id="content-main">
        <form action="" method="post">
            {% csrf_token %}
            <div>
                <fieldset class="module aligned {{ fieldset.classes }}">
                    <h2 class="header">Group Setup</h2>
                    <div class="form-row field-name">
                        <label class="required" for="organization_short">Organization Short Name: </label>
                        <input type="text" class="vTextField" id="organization_short" name="organization_short"
                               placeholder="ACME" required=""/>
                        <div class="help">We will use this for the group name and composites</div>
                    </div>
                    <div class="form-row field-name">
                        <label for="project_short">Project Short Name: </label>
                        <input type="text" class="vTextField" id="project_short" name="project_short" placeholder="Safebox"/>
                        <div class="help">We will use this for the composites too (optional)</div>
                    </div>
                    <div class="form-row field-name">
                        <label class="required" for="country_code">Country code (2 letters): </label>
                        <input type="text" class="vTextField" id="country_code" name="country_code" placeholder="PT" required=""/>
                        <div class="help">This is where the project takes place</div>
                    </div>

                </fieldset>
                <fieldset class="module aligned {{ fieldset.classes }}">
                    <div class="clearfix">
                        <h2 class="description">Object Creation</h2>
                    </div>

                    <div class="container">
                        <div class="form-row field-name">
                            <label class="required" for="id_aggregationlayer">Aggregation Layer ID: </label>
                            <input type="text" name="aggregationlayer" id="id_aggregationlayer" required=""
                                   class="vForeignKeyRawIdAdminField">
                            <a href="/admin/raster_aggregation/aggregationlayer/?_to_field=id&_popup=1"
                               class="related-lookup" id="lookup_id_aggregationlayer" title="Lookup"></a>
                        </div>
                        <div class="form-row filed-name">
                            <label class="required" for="id_date_start">Start date:</label>
                            <p class="datetime">
                                <input type="text" name="id_date_start" class="vDateField" size="10" required=""
                                       id="id_date_start"><span class="datetimeshortcuts"></span>
                            </p>
                        </div>
                        <div class="form-row filed-name">
                            <label class="required" for="id_date_end">End date:</label>
                            <p class="datetime">
                                <input type="text" name="id_date_end" class="vDateField" size="10" required=""
                                       id="id_date_end"><span class="datetimeshortcuts"></span>
                            </p>
                        </div>
                        <div class="form-row field-name">
                            <label for="sentinel_1">Include Sentinel 1?</label>
                            <input type="checkbox" id="sentinel_1" name="sentinel_1">
                        </div>
                        <div class="form-row field-name">
                            <label for="sentinel_2">Include Sentinel 2?</label>
                            <input type="checkbox" id="sentinel_2" name="sentinel_2" checked="">
                        </div>
                        <div class="form-row field-name">
                            <label class="required" for="cloudy_percent">Cloudy percentage: </label>
                            <input type="number" class="vTextField" id="cloudy_percent" name="cloudy_percent" required="" value="69"
                                   min="0" max="100"/>
                        </div>
                    </div>
                </fieldset>

                <div class="submit-row">
                    {% for obj in queryset %}
                        <input type="hidden" name="{{ action_checkbox_name }}" value="{{ obj.pk }}"/>
                    {% endfor %}
                    <input type="hidden" name="action" value="initialize_new_customer"/>
                    <input type="submit" name="apply" value="Initialize new customer"/>
                </div>
            </div>
            {% block admin_change_form_document_ready %}
                {{ block.super }}
                <script src="{% static 'app/formset_handlers.js' %}"></script>
            {% endblock %}
        </form>
    </div>
{% endblock %}

apps/auth_admin/templates/upgrade_group.html
{% extends "admin/base_site.html" %}
{% load i18n admin_urls static admin_modify %}


{% block extrahead %}{{ block.super }}
    <script type="text/javascript" src="{% url 'admin:jsi18n' %}"></script>
    {{ media }}
{% endblock %}

{% block extrastyle %}{{ block.super }}
    <link rel="stylesheet" type="text/css" href="{% static "admin/css/forms.css" %}">{% endblock %}

{% block coltype %}colM{% endblock %}

{% block bodyclass %}{{ block.super }} app-{{ opts.app_label }} model-{{ opts.model_name }} change-form{% endblock %}


{% block content %}
    <div id="content-main">
        <form action="" method="post">
            {% csrf_token %}
            <div>
                <fieldset class="module aligned">
                    <h2 class="header">Create users for the production Group (at least 1)</h2>
                    <div class="js-inline-admin-formset inline-group" id="user_set-group"
                         data-inline-type="tabular"
                         data-inline-formset="{&quot;name&quot;: &quot;#user_set&quot;, &quot;options&quot;: {&quot;prefix&quot;: &quot;user_set&quot;, &quot;addText&quot;: &quot;Add another User&quot;, &quot;deleteText&quot;: &quot;Remove&quot;}}">
                        <div class="tabular inline-related last-related">
                            <input type="hidden" name="user_set-TOTAL_FORMS" value="0"
                                   id="id_user_set-TOTAL_FORMS" autocomplete="off">
                            <input type="hidden"
                                   name="user_set-INITIAL_FORMS"
                                   value="1"
                                   id="id_user_set-INITIAL_FORMS">
                            <input type="hidden" name="user_set-MIN_NUM_FORMS" value="1"
                                   id="id_user_set-MIN_NUM_FORMS">
                            <input type="hidden"
                                   name="user_set-MAX_NUM_FORMS"
                                   value="10"
                                   id="id_user_set-MAX_NUM_FORMS"
                                   autocomplete="off">
                            <fieldset class="module">
                                <table>
                                    <thead>
                                    <tr>
                                        <th class="original"></th>
                                        <th class="column-first-name required">First Name
                                        </th>
                                        <th class="column-last-name required">Last Name
                                        </th>
                                        <th class="column-email required">Email
                                        </th>
                                        <th class="column-language required">Language
                                        </th>
                                        <th class="column-token">Create token?
                                        </th>
                                        <th>Delete?</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    <tr class="form-row empty-form row1" id="user_set-empty">
                                        <td class="original">
                                            <input type="hidden" name="user_set-__prefix__-id"
                                                   id="id_user_set-__prefix__-id">
                                        </td>
                                        <td class="field-first-name">
                                            <input type="text" name="user_set-__prefix__-first-name" class="vTextField"
                                                   maxlength="50" id="id_user_set-__prefix__-first-name">
                                        </td>
                                        <td class="field-last-name">
                                            <input type="text" name="user_set-__prefix__-last-name" class="vTextField"
                                                   maxlength="50" id="id_user_set-__prefix__-last-name">
                                        </td>
                                        <td class="field-email">
                                            <input type="text" name="user_set-__prefix__-email" class="vTextField"
                                                   maxlength="100" id="id_user_set-__prefix__-email">
                                        </td>
                                        <td class="field-language">
                                            <select name="user_set-__prefix__-language"
                                                    id="id_user_set-__prefix__-language">
                                                <option value="" selected="">---------</option>
                                                <option value="english">English</option>
                                                <option value="portuguese">Portuguese</option>
                                                <option value="klingon">Klingon</option>
                                            </select>
                                        </td>
                                        <td class="field-token">
                                            <input type="checkbox" name="user_set-__prefix__-token"
                                                   id="id_user_set-__prefix__-token">
                                        </td>
                                        <td class="delete"></td>
                                    </tr>
                                    </tbody>
                                </table>
                            </fieldset>
                        </div>
                    </div>
                </fieldset>
                <fieldset class="module aligned {{ fieldset.classes }}">
                    <div class="clearfix">
                        <h2 class="description">Understand the consequences of your actions</h2>
                    </div>
                    <div class="form-row field-name">
                        <label class="required" for="sure" >Are you sure to proceed?</label>
                        <input type="checkbox" name="sure" id="sure">
                        <div class="help">By clicking this checkbox and the button you agree to bear with all the
                            consequences this action could start.
                        </div>
                    </div>
                </fieldset>
                <div class="submit-row">
                    <input type="hidden" name="{{ action_checkbox_name }}" value="{{ group.pk }}"/>
                    <input type="hidden" name="action" value="upgrade_test_group"/>
                    <input type="submit" name="apply" value="Upgrade test group"/>
                </div>
            </div>
        </form>
    </div>
{% endblock %}